name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - name: Build and test with Rake
      run: |
        gem install bundler
        sudo apt-get install libimlib2-dev aspell aspell-en
        bundle install --jobs 4 --retry 3
        bundle exec rake
